# Generated by Django 5.2.17 on 2026-09-12 09:25

import apps.accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('full_name', models.CharField(max_length=150, verbose_name='nome completo')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='endereco')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='complemento')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='codigo postal')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='estado / provincia')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='pais')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, help_text='Define se o usuario pode acessar a area administrativa.', verbose_name='acesso a administracao')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='cadastrado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['full_name', 'email'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
