# Generated by Django 5.2.17 on 2026-09-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['full_name', 'email'], 'permissions': [('manage_users', 'Pode administrar usuários (ativar, desativar, alterar função)')], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
