# Generated by Django 5.2.17 on 2026-09-20 21:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_confirmacao_de_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='telefone confirmado em'),
        ),
        migrations.CreateModel(
            name='ConfirmacaoDeTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='telefone')),
                ('code_hash', models.CharField(max_length=255, verbose_name='codigo (hash)')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='enviado em')),
                ('expires_at', models.DateTimeField(verbose_name='expira em')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacao_de_telefone', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'confirmacao de telefone',
                'verbose_name_plural': 'confirmacoes de telefone',
            },
        ),
    ]
