# Generated by Django 5.2.17 on 2026-09-12 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='identificador')),
                ('kind', models.CharField(choices=[('text', 'Texto simples'), ('rich_text', 'Texto formatado'), ('image', 'Imagem')], default='text', max_length=20, verbose_name='tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'bloco de conteúdo',
                'verbose_name_plural': 'blocos de conteúdo',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('language', models.CharField(choices=[('pt', 'Portugues'), ('fr', 'Frances'), ('nl', 'Holandes'), ('en', 'Ingles')], max_length=8, verbose_name='idioma')),
                ('content', models.TextField(blank=True, verbose_name='conteúdo')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.contentblock', verbose_name='bloco')),
            ],
            options={
                'verbose_name': 'tradução de conteúdo',
                'verbose_name_plural': 'traduções de conteúdo',
                'ordering': ['block', 'language'],
                'constraints': [models.UniqueConstraint(fields=('block', 'language'), name='content_unique_translation_per_language')],
            },
        ),
    ]
