# Generated by Django 5.2.17 on 2026-09-12 16:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('key', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='identificador')),
                ('kind', models.CharField(choices=[('logo', 'Logomarca'), ('favicon', 'Favicon'), ('home', 'Imagem da Home'), ('partner', 'Imagem de parceiro'), ('content', 'Imagem de conteúdo'), ('other', 'Outro')], default='other', max_length=20, verbose_name='tipo')),
                ('file', models.ImageField(upload_to='assets/%Y/%m/', verbose_name='arquivo')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='texto alternativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
                'ordering': ['kind', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('key', models.SlugField(max_length=60, unique=True, verbose_name='identificador')),
                ('name', models.CharField(help_text='Uso interno, no backoffice.', max_length=150, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'página',
                'verbose_name_plural': 'páginas',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='contenttranslation',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_translations', to='content.asset', verbose_name='imagem'),
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('key', models.SlugField(blank=True, help_text='Opcional; útil para referenciar a seção a partir de um link interno.', max_length=80, verbose_name='identificador')),
                ('kind', models.CharField(choices=[('hero', 'Destaque (hero)'), ('text', 'Texto'), ('image_text', 'Imagem e texto'), ('features', 'Destaques / recursos'), ('partners', 'Parceiros'), ('faq', 'Perguntas frequentes'), ('cta', 'Chamada para ação'), ('banner', 'Banner'), ('contact', 'Contato')], max_length=20, verbose_name='tipo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Posição na página. Não precisa ser sequencial nem única.', verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page', verbose_name='página')),
            ],
            options={
                'verbose_name': 'seção de página',
                'verbose_name_plural': 'seções de página',
                'ordering': ['page', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('site_name', models.CharField(default='Desenrola', max_length=150, verbose_name='nome do site')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de contato')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='telefone de contato')),
                ('contact_address', models.TextField(blank=True, verbose_name='endereço')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='redes sociais')),
                ('theme_primary_color', models.CharField(default='#1a5fd6', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor em hexadecimal, no formato #rrggbb.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='cor principal')),
                ('theme_success_color', models.CharField(default='#17a34a', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor em hexadecimal, no formato #rrggbb.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='cor de sucesso')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.asset', verbose_name='favicon')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.asset', verbose_name='logomarca')),
            ],
            options={
                'verbose_name': 'configurações do site',
                'verbose_name_plural': 'configurações do site',
            },
        ),
        migrations.CreateModel(
            name='PageSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('language', models.CharField(choices=[('pt', 'Portugues'), ('fr', 'Frances'), ('nl', 'Holandes'), ('en', 'Ingles')], max_length=8, verbose_name='idioma')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Estrutura livre, definida pelo tipo da seção (título, texto, botão...).', verbose_name='conteúdo')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.pagesection', verbose_name='seção')),
            ],
            options={
                'verbose_name': 'tradução de seção',
                'verbose_name_plural': 'traduções de seção',
                'ordering': ['section', 'language'],
                'constraints': [models.UniqueConstraint(fields=('section', 'language'), name='content_unique_section_translation_per_language')],
            },
        ),
    ]
