# Generated by Django 5.2.17 on 2026-09-12 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='identificador interno')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('language', models.CharField(choices=[('pt', 'Portugues'), ('fr', 'Frances'), ('nl', 'Holandes'), ('en', 'Ingles')], max_length=8, verbose_name='idioma')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('default_field_schema', models.JSONField(blank=True, default=dict, help_text='Estrutura de referência dos campos do formulário, usada como ponto de partida ao criar uma nova versão. Editada pelo futuro editor visual.', verbose_name='schema padrão dos campos')),
            ],
            options={
                'verbose_name': 'modelo de carta',
                'verbose_name_plural': 'modelos de carta',
                'ordering': ['name', 'language'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('version_number', models.PositiveIntegerField(verbose_name='número da versão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('inactive', 'Inativa')], default='draft', max_length=12, verbose_name='status')),
                ('field_schema', models.JSONField(blank=True, default=dict, verbose_name='configuração dos campos')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='snapshot de reprodução')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicada em')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='doctemplates.lettertemplate', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'versão de modelo',
                'verbose_name_plural': 'versões de modelo',
                'ordering': ['template', '-version_number'],
                'permissions': [('publish_templateversion', 'Pode publicar uma versão de modelo')],
                'constraints': [models.UniqueConstraint(fields=('template', 'version_number'), name='doctemplates_unique_version_per_template')],
            },
        ),
    ]
