# Generated by Django 5.2.17 on 2026-09-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctemplates', '0004_passport_placeholder_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(help_text='Identificador estável, gravado na carta. Não mude depois de existirem cartas usando-o.', max_length=16, unique=True, verbose_name='código')),
                ('is_active', models.BooleanField(default=True, help_text='Só nacionalidades ativas aparecem no formulário.', verbose_name='ativa')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='ordem')),
                ('name_pt', models.CharField(max_length=120, verbose_name='nome (pt)')),
                ('name_fr', models.CharField(max_length=120, verbose_name='nome (fr)')),
                ('name_nl', models.CharField(max_length=120, verbose_name='nome (nl)')),
                ('name_en', models.CharField(max_length=120, verbose_name='nome (en)')),
                ('guest_form', models.CharField(help_text='Como sai na tabela do documento. Ex.: "Brésilienne".', max_length=120, verbose_name='forma no documento — convidado')),
                ('host_form', models.CharField(help_text='Como sai no texto do documento. Ex.: "belge".', max_length=120, verbose_name='forma no documento — anfitrião')),
            ],
            options={
                'verbose_name': 'nacionalidade',
                'verbose_name_plural': 'nacionalidades',
                'ordering': ['order', 'name_pt'],
            },
        ),
    ]
