# Generated by Django 5.2.17 on 2026-09-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctemplates', '0007_schema_anfitriao_vem_do_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateversion',
            name='visual_schema',
            field=models.JSONField(blank=True, default=dict, help_text='Posições e estilos dos elementos do documento, em pontos. Editado pelo editor visual do backoffice.', verbose_name='modelo visual'),
        ),
    ]
