# Generated by Django 5.2.17 on 2026-09-13 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctemplates', '0008_visual_schema_do_editor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('page', models.JSONField(default=dict, verbose_name='página')),
                ('data_sources', models.JSONField(blank=True, default=list, verbose_name='fontes de dados')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documento',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='identificador')),
                ('language', models.CharField(choices=[('pt', 'Portugues'), ('fr', 'Frances'), ('nl', 'Holandes'), ('en', 'Ingles')], max_length=8, verbose_name='idioma')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_system', models.BooleanField(default=False, help_text='Modelo oficial do Desenrola. Serve de base; não é apagado.', verbose_name='modelo do sistema')),
                ('is_locked', models.BooleanField(default=False, help_text='Fechado para edição neste momento.', verbose_name='travado')),
                ('field_schema', models.JSONField(blank=True, default=dict, verbose_name='configuração dos campos')),
                ('layout', models.JSONField(blank=True, default=dict, verbose_name='layout')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('duplicated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='doctemplates.documenttemplate', verbose_name='duplicado de')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='doctemplates.documenttype', verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'modelo de documento',
                'verbose_name_plural': 'modelos de documento',
                'ordering': ['type', '-is_system', 'language', 'name'],
            },
        ),
    ]
