# Generated by Django 5.2.17 on 2026-09-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracao_de_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='bcc_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='enviar cópia oculta para'),
        ),
    ]
