# Generated by Django 5.2.17 on 2026-09-12 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctemplates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador público')),
                ('language', models.CharField(choices=[('pt', 'Portugues'), ('fr', 'Frances'), ('nl', 'Holandes'), ('en', 'Ingles')], max_length=8, verbose_name='idioma')),
                ('reference', models.CharField(editable=False, max_length=40, unique=True, verbose_name='referência')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('generated', 'Gerada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='draft', max_length=12, verbose_name='status')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='dados preenchidos')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='snapshot da geração')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='gerada em')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='letters/%Y/%m/', verbose_name='arquivo PDF')),
                ('pdf_sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256 do PDF')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letters', to='doctemplates.lettertemplate', verbose_name='modelo')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letters', to='doctemplates.templateversion', verbose_name='versão do modelo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'carta',
                'verbose_name_plural': 'cartas',
                'ordering': ['-created_at'],
                'permissions': [('view_all_letters', 'Pode visualizar cartas de todos os usuários')],
            },
        ),
    ]
