# Generated by Django 5.2.17 on 2026-09-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0006_idiomas_do_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('key', models.SlugField(help_text='Nome interno com que a resposta fica gravada na carta. Não muda quando o texto muda.', max_length=60, unique=True, verbose_name='identificador')),
                ('text', models.TextField(help_text='Texto simples, na primeira pessoa ("Declaro estar ciente...").', verbose_name='texto da declaração')),
                ('is_active', models.BooleanField(default=True, help_text='Só declarações ativas aparecem no assistente.', verbose_name='ativa')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'declaração do assistente',
                'verbose_name_plural': 'declarações do assistente',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
