# Generated by Django 5.2.17 on 2026-09-16 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_pagesection_contador_e_carrossel'),
        ('letters', '0008_semear_declaracoes_do_assistente'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('language', models.CharField(choices=[('pt', 'Portugues'), ('fr', 'Frances'), ('nl', 'Holandes'), ('en', 'Ingles')], max_length=8, unique=True, verbose_name='idioma')),
                ('asset', models.ForeignKey(blank=True, help_text='Sem imagem, o assistente desenha a bandeira padrão.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_flags', to='content.asset', verbose_name='imagem da bandeira')),
            ],
            options={
                'verbose_name': 'bandeira de idioma',
                'verbose_name_plural': 'bandeiras dos idiomas',
                'ordering': ['language'],
            },
        ),
    ]
