# Generated by Django 5.2.17 on 2026-09-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0010_idioma_padrao_frances'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterpolicy',
            name='generation_requirement',
            field=models.CharField(choices=[('nenhuma', 'Não exigir nenhuma confirmação'), ('email', 'Exigir confirmação de e-mail'), ('email_e_telefone', 'Exigir confirmação de e-mail e telefone')], default='nenhuma', max_length=32, verbose_name='validação para gerar carta convite'),
        ),
    ]
